version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.docker
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-data:/data

volumes:
  redis-data:
    driver: local
  docker-nest-postgres: